packages:
  - 'apps/*'
  - 'packages/*'
  - 'crates/*'

catalog:
  vite: 5.2.13
catalogs:
  svelte:
    svelte: 5.0.0-next.260
    '@sveltejs/kit': 2.6.1
    svelte-check: 4.0.4
    '@sveltejs/vite-plugin-svelte': 4.0.0-next.7
    '@sveltejs/adapter-static': 3.0.5
