packages:
  - 'apps/*'
  - 'packages/*'
  - 'crates/*'

catalog:
  vite: 5.4.10
catalogs:
  svelte:
    svelte: 5.1.9
    '@sveltejs/kit': 2.7.3
    svelte-check: 4.0.5
    '@sveltejs/vite-plugin-svelte': 4.0.0
    '@sveltejs/adapter-static': 3.0.6
