[package]
name = "gitbutler-project-store"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"
doctest = false
test = false

[dependencies]
rusqlite = { version = "0.31.0", features = ["bundled", "uuid"] }
anyhow = "1.0.86"
uuid.workspace = true