[package]
name = "gitbutler-review"
version = "0.0.0"
edition = "2021"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false

[dependencies]
git2.workspace = true
anyhow.workspace = true
bstr.workspace = true
gitbutler-branch.workspace = true
gitbutler-commit.workspace = true
gitbutler-repo.workspace = true
gitbutler-branch-actions.workspace = true
gitbutler-stack.workspace = true
gitbutler-cherry-pick.workspace = true
serde.workspace = true
