name: E2E Tests
on:
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      sha:
        type: string
        required: false
        description: Target SHA

jobs:
  test:
    name: Run WebdriverIO Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gitbutlerapp/e2e-runner:latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event_name != 'workflow_dispatch' }}
      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          ref: ${{ github.event.inputs.sha }}
      - name: Build CLI
        run: cargo build -p gitbutler-cli
      - name: Build SvelteKit
        run: pnpm build:desktop -- --mode development
      - name: Build Tauri
        run: pnpm build:test
      - name: WebdriverIO
        run: xvfb-run pnpm test:e2e

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: WebdriverIO Artifacts
          overwrite: true
          path: |
            ./apps/desktop/e2e/videos
            ~/.config/com.gitbutler.app*/logs
